# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_auto_20171018_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quran',
            name='berat',
        ),
    ]
