# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0003_remove_quran_berat'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran',
            name='gambar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
