# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0006_auto_20171020_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='gambar',
            field=models.ImageField(upload_to='utama'),
        ),
    ]
