# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0008_auto_20171020_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quran',
            name='gambar',
        ),
    ]
