# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0009_remove_quran_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran',
            name='gambar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
