# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0015_auto_20171023_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
