# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0019_auto_20171023_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='harga',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
