# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0023_auto_20171023_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
