# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0027_auto_20171023_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quran',
            name='berat',
        ),
    ]
